//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the MIT License. See License.txt in the project root for
license information.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ErrorObj) DeepCopyInto(out *ErrorObj) {
	*out = *in
	in.UpdatedTimeStamp.DeepCopyInto(&out.UpdatedTimeStamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ErrorObj.
func (in *ErrorObj) DeepCopy() *ErrorObj {
	if in == nil {
		return nil
	}
	out := new(ErrorObj)
	in.DeepCopyInto(out)
	return out
}


// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KV) DeepCopyInto(out *KV) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KV.
func (in *KV) DeepCopy() *KV {
	if in == nil {
		return nil
	}
	out := new(KV)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningError) DeepCopyInto(out *ProvisioningError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningError.
func (in *ProvisioningError) DeepCopy() *ProvisioningError {
	if in == nil {
		return nil
	}
	out := new(ProvisioningError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisioningStatus) DeepCopyInto(out *ProvisioningStatus) {
	*out = *in
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(ProvisioningError)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisioningStatus.
func (in *ProvisioningStatus) DeepCopy() *ProvisioningStatus {
	if in == nil {
		return nil
	}
	out := new(ProvisioningStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootApp) DeepCopyInto(out *SpringBootApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootApp.
func (in *SpringBootApp) DeepCopy() *SpringBootApp {
	if in == nil {
		return nil
	}
	out := new(SpringBootApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpringBootApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootAppList) DeepCopyInto(out *SpringBootAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpringBootApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootAppList.
func (in *SpringBootAppList) DeepCopy() *SpringBootAppList {
	if in == nil {
		return nil
	}
	out := new(SpringBootAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpringBootAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootAppSpec) DeepCopyInto(out *SpringBootAppSpec) {
	*out = *in
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.JvmOptions != nil {
		in, out := &in.JvmOptions, &out.JvmOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ApplicationConfigurations != nil {
		in, out := &in.ApplicationConfigurations, &out.ApplicationConfigurations
		*out = make([]*KV, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(KV)
				**out = **in
			}
		}
	}
	if in.Certificates != nil {
		in, out := &in.Certificates, &out.Certificates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StaticContentLocations != nil {
		in, out := &in.StaticContentLocations, &out.StaticContentLocations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BindingPorts != nil {
		in, out := &in.BindingPorts, &out.BindingPorts
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
	if in.Miscs != nil {
		in, out := &in.Miscs, &out.Miscs
		*out = make([]*KV, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(KV)
				**out = **in
			}
		}
	}
	in.LastModifiedTime.DeepCopyInto(&out.LastModifiedTime)
	in.LastUpdatedTime.DeepCopyInto(&out.LastUpdatedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootAppSpec.
func (in *SpringBootAppSpec) DeepCopy() *SpringBootAppSpec {
	if in == nil {
		return nil
	}
	out := new(SpringBootAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootAppStatus) DeepCopyInto(out *SpringBootAppStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootAppStatus.
func (in *SpringBootAppStatus) DeepCopy() *SpringBootAppStatus {
	if in == nil {
		return nil
	}
	out := new(SpringBootAppStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootServer) DeepCopyInto(out *SpringBootServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootServer.
func (in *SpringBootServer) DeepCopy() *SpringBootServer {
	if in == nil {
		return nil
	}
	out := new(SpringBootServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpringBootServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootServerList) DeepCopyInto(out *SpringBootServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpringBootServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootServerList.
func (in *SpringBootServerList) DeepCopy() *SpringBootServerList {
	if in == nil {
		return nil
	}
	out := new(SpringBootServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpringBootServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootServerSpec) DeepCopyInto(out *SpringBootServerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootServerSpec.
func (in *SpringBootServerSpec) DeepCopy() *SpringBootServerSpec {
	if in == nil {
		return nil
	}
	out := new(SpringBootServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootServerStatus) DeepCopyInto(out *SpringBootServerStatus) {
	*out = *in
	in.ProvisioningStatus.DeepCopyInto(&out.ProvisioningStatus)
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]ErrorObj, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootServerStatus.
func (in *SpringBootServerStatus) DeepCopy() *SpringBootServerStatus {
	if in == nil {
		return nil
	}
	out := new(SpringBootServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootSite) DeepCopyInto(out *SpringBootSite) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootSite.
func (in *SpringBootSite) DeepCopy() *SpringBootSite {
	if in == nil {
		return nil
	}
	out := new(SpringBootSite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpringBootSite) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootSiteList) DeepCopyInto(out *SpringBootSiteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpringBootSite, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootSiteList.
func (in *SpringBootSiteList) DeepCopy() *SpringBootSiteList {
	if in == nil {
		return nil
	}
	out := new(SpringBootSiteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpringBootSiteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootSiteSpec) DeepCopyInto(out *SpringBootSiteSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootSiteSpec.
func (in *SpringBootSiteSpec) DeepCopy() *SpringBootSiteSpec {
	if in == nil {
		return nil
	}
	out := new(SpringBootSiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootSiteStatus) DeepCopyInto(out *SpringBootSiteStatus) {
	*out = *in
	in.ProvisioningStatus.DeepCopyInto(&out.ProvisioningStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootSiteStatus.
func (in *SpringBootSiteStatus) DeepCopy() *SpringBootSiteStatus {
	if in == nil {
		return nil
	}
	out := new(SpringBootSiteStatus)
	in.DeepCopyInto(out)
	return out
}